# Generated by Django 3.1.7 on 2021-03-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetroStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField()),
                ('station_name', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('outflow', models.IntegerField()),
                ('outflow_pred', models.IntegerField()),
                ('inflow', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=10)),
                ('algo', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('color', models.CharField(max_length=20)),
                ('shape', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RoadYX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=10)),
                ('algo', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('color', models.CharField(max_length=20)),
                ('shape', models.TextField()),
            ],
        ),
    ]
